# create_datebase.yml
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:

  # Run apt update && apt upgrade
    - name: sudo apt update && sudo apt upgrade 
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #one day
  # Create new database
    - name: Create a new database with name "acme" and specific encoding and locale # settings.
      postgresql_db:
        name: {{ database_name }}
        encoding: UTF-8

    - name: Connect to acme database, create django user, and grant access to database and products table
      postgresql_user:
        db: {{ database_name }}
        name: {{ database_user }}
        password: {{ database_password }}
        priv: "CONNECT/products:ALL"
        expires: "Jan 31 2020"

# postgres=# ALTER ROLE myprojectuser SET client_encoding TO 'utf8';
# postgres=# ALTER ROLE myprojectuser SET default_transaction_isolation TO 'read committed';
# postgres=# ALTER ROLE myprojectuser SET timezone TO 'UTC';
# postgres=# GRANT ALL PRIVILEGES ON DATABASE myproject TO myprojectuser;