# install_django.yml
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:

  # Run apt update && apt upgrade
    - name: sudo apt update && sudo apt upgrade 
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #one day
  
  # Pull Django project down from GitHub
    - name: git pull django project from GitHub
      git:
        repo: "{{ project_repo }}"
        dest: "{{ app_dir }}"
        force: yes

  # Create Virtual Env and install Python packages
    - name: pip install /my_app/requirements.txt
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ app_dir }}/venv"

  # Copy .env file
    - name: copy .env file to /home/user/appdir/.env
      template:
        src: templates/.env.j2
        dest: "{{ app_dir }}/.env"
  
  # change permissions of whole app_dir
    - name: Recursively change ownership of a directory
      file:
        path: "{{ app_dir }}"
        state: directory
        recurse: yes
        group: wheel
        mode: '0775'

  # Run Django collectstatic
    - name: Run manage.py collectstatic
      community.general.django_manage:
        command: collectstatic
        app_path: "{{ app_dir }}"
        virtualenv: "{{ app_dir }}/venv"

  # Run Django manage.py makemigrations
    - name: Run manage.py makemigrations
      community.general.django_manage:
        command: makemigrations
        app_path: "{{ app_dir }}"
        virtualenv: "{{ app_dir }}/venv"

  # Run Django manage.py migrate
    - name: Run manage.py migrate
      community.general.django_manage:
        command: migrate
        app_path: "{{ app_dir }}"
        virtualenv: "{{ app_dir }}/venv"

    - name: Load the initial_data fixture into the application
      community.general.django_manage:
        command: loaddata
        app_path: "{{ app_dir }}"
        fixtures: "{{ fixture_path }}"
        virtualenv: "{{ app_dir }}/venv"

  # Change allowed hosts to include the server IP address
    - name: add server IP address to allowed hosts
      lineinfile:
        path: "{{ app_dir }}/{{ django_project_name }}/settings.py"
        state: present
        regexp: '^ALLOWED_HOSTS = '
        line: "ALLOWED_HOSTS = ['{{ server_IP }}','{{ domain_name }}']"
