# install_django.yml
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:

  # Run apt update && apt upgrade
    - name: sudo apt update && sudo apt upgrade 
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #one day
  
  # Pull Django project down from GitHub
    - name: git pull django project from GitHub
      git:
        repo: "{{ project_repo }}"
        dest: "{{ app_dir }}"

  # Create Virtual Env and install Python packages
    - name: pip install /my_app/requirements.txt
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ app_dir }}/venv"

  # Update Django project files for deployment

  # Run Django collect static

  # Run Django make migrations, migrate

  # Run Django createsuperuser
  