# install_nginx.yml
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:

  # Run apt update && apt upgrade
    - name: sudo apt update && sudo apt upgrade 
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #one day
  # Ensure nginx is installed

  # Copy nginx config files

  # Ensure nginx is enabled

  # Ensure nginx is running