# install_django.yml
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:

  # Run apt update && apt upgrade
    - name: sudo apt update && sudo apt upgrade 
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #one day
    - name: git pull django project
    - name: pip install /my_app/requirements.txt
      pip:
        requirements: /my_app/requirements.txt
        virtualenv: /my_app/venv
