# install_gunicorn.yml
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:

  # Run apt update && apt upgrade
    - name: sudo apt update && sudo apt upgrade 
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #one day

  # Ensure gunicorn is installed
    - name: pip install gunicorn
      pip:
        name: gunicorn
        virtualenv: "{{ app_dir }}/venv"

  # Copy gunicorn socket file
    - name: copy gunicorn socket file to /etc/systemd/system/gunicorn.socket
      template:
        src: templates/gunicorn.socket.j2
        dest: /etc/systemd/system/gunicorn.socket

  # Copy gunicorn systemd file
    - name: copy gunicorn systemd file to /etc/systemd/system/gunicorn.service
      template:
        src: templates/gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service
        
  # Ensure gunicorn socket and system service is running
    - name: force systemd to reread configs (2.4 and above)
      systemd:
        daemon_reload: yes
    - name: Start/Make sure the gunicorn.socket systemd service is running
      systemd:
        state: started
        name: gunicorn.socket
    - name: Start/Make sure the gunicorn systemd service is running
      systemd:
        state: started
        name: gunicorn
