# install_gunicorn.yml
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:

  # Run apt update && apt upgrade
    - name: sudo apt update && sudo apt upgrade 
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #one day
  # Ensure gunicorn is installed

  # Copy gunicorn sock files

  # Copy gunicorn systemd files

  # Ensure gunicorn system service is enabled

  # Ensure gunicorn system service is running
  